version: 0.1

phases:
  install:
    commands:
      - echo "Nothing to install"
  pre_build:
    commands:
      - echo "Running pre-build"
      - bash bin/build.sh
  build:
    commands:
      - echo "Starting CloudFormation package build"
      - aws cloudformation package --template-file app-sam.yaml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file app-output_sam.yaml
  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - app-output_sam.yaml
  discard-paths: yes
